import type { Page } from '@playwright/test'
import type { AcknowledgedSessionMessage, ContextAttachment } from './helpers/attention'
import { Buffer } from 'node:buffer'
import { createHash } from 'node:crypto'
import { expect, test } from '@playwright/test'
import { attentionAttachment, attentionSnapshot, canonicalContextArray, canonicalContextValue, capturedHttpStageMetrics, installAttentionWireTap, resolvedContextAttachments } from './helpers/attention'
import { ATTENTION_ORACLE_LIMITS, attentionSnapshotFromAttachment, attentionSnapshotsFromAttachments, expandAttentionV2ForTest, expandAttentionV3ForTest, oracleCanonicalJson } from './helpers/attention-v2'

// Fixed cross-language wire bytes, not generated by the production encoder.
const COMPACT_VECTOR = '{"candidates":[{"action_ref":{"generation":1,"host_instance_id":"host-1","mount_id":"leaf-1","path_digest":"sha256:2c46a9ab38e76737a2418025f51d2c7f2f3d743bedaba84a04598fb2aed7758f","rect":{"height":24,"width":80,"x":100,"y":100},"snapshot_id":"snapshot-1","target_id":"target-1"},"occluded":false,"path_indices":[0,1],"rect":{"height":24,"width":80,"x":100,"y":100},"sample_refs":[0],"summary":{"name":"Nested status","role":"status","text":"Ready"},"target_id":"target-1"}],"capture":{"complete":true,"duration_ms":12,"grid_step_css_px":5,"points":[{"point_id":"p0","x":120,"y":112}],"radius_css_px":20,"sampled_points":1},"coordinate_space":{"device_pixel_ratio":1,"height":720,"kind":"host-viewport","width":1280},"created_at":"2026-09-04T12:00:00.000Z","host_instance_id":"host-1","mount_generation":3,"omissions":[],"path_dictionary":[{"generation":3,"kind":"host","mount_id":"host-1"},{"generation":1,"kind":"element","mount_id":"leaf-1","tag_name":"span"}],"recent_events":[],"schema":"wippy.attention.v2","snapshot_id":"snapshot-1"}'

function compactPayload() {
  return JSON.parse(COMPACT_VECTOR)
}

function oracleAttachment(payload = compactPayload(), version = 2, id = 'oracle-fixture'): ContextAttachment {
  const content = oracleCanonicalJson(payload)
  return { attachment_id: id, kind: 'wippy.attention', version, content_type: 'application/json',
    content, content_bytes: Buffer.byteLength(content), content_hash: `sha256:${createHash('sha256').update(content).digest('hex')}`,
    created_at: '2026-09-04T12:00:00.000Z' }
}

function latticePayload() {
  const payload = compactPayload()
  delete payload.capture.points
  payload.capture.point_encoding = { kind: 'css-euclidean-grid.v1', origin: { x: 120, y: 112 } }
  payload.capture.sampled_points = 49
  payload.candidates[0].sample_refs = [[0, 49]]
  return payload
}

function packedV3Payload() {
  const payload = compactPayload()
  payload.schema = 'wippy.attention.v3'
  payload.path_dictionary = payload.path_dictionary.map((segment: Record<string, unknown>) => {
    const { kind, mount_id, generation, rect, clip_rect, local_to_parent, ...attributes } = segment
    if (rect) {
      const value = rect as Record<string, number>
      attributes.rect = [value.x, value.y, value.width, value.height]
    }
    if (clip_rect) {
      const value = clip_rect as Record<string, number>
      attributes.clip_rect = [value.x, value.y, value.width, value.height]
    }
    if (local_to_parent)
      attributes.local_to_parent = (local_to_parent as { matrix: number[] }).matrix
    return [kind, mount_id, generation, attributes]
  })
  return payload
}

test('independent oracle preserves the fixed 1040-byte vector and complete action path', () => {
  expect(Buffer.byteLength(COMPACT_VECTOR)).toBe(1040)
  expect(createHash('sha256').update(COMPACT_VECTOR).digest('hex')).toBe('d20ab08a1a88e882421a2a1f6187b261db1c6c56532f006a518fb0ce8aedf5f5')
  const attachment = oracleAttachment()
  const original = JSON.stringify(attachment)
  const snapshot = attentionSnapshotFromAttachment(attachment)
  expect(snapshot.candidates[0].path).toEqual([
    { generation: 3, kind: 'host', mount_id: 'host-1' },
    { generation: 1, kind: 'element', mount_id: 'leaf-1', tag_name: 'span' },
  ])
  expect(snapshot.candidates[0].sample_point_ids).toEqual(['p0'])
  expect(snapshot.candidates[0].action_ref?.path_digest).toBe('sha256:2c46a9ab38e76737a2418025f51d2c7f2f3d743bedaba84a04598fb2aed7758f')
  expect(snapshot.schema).toBe('wippy.attention.v1')
  expect(JSON.stringify(attachment)).toBe(original)
  const command = { type: 'session_message' as const, session_id: 'session-1', request_id: 'request-1', message_id: 'message-1', data: { text: 'fixture', context_attachments: [attachment] } }
  expect(attentionSnapshot(command)).toEqual(snapshot)
  expect(command.data.context_attachments[0].version).toBe(2)
  expect(command.data.context_attachments[0].content).toBe(COMPACT_VECTOR)
  const v1 = oracleAttachment(snapshot, 1)
  v1.expires_at = '2026-09-04T13:00:00.000Z'
  expect(attentionSnapshotFromAttachment(v1)).toEqual(snapshot)
})

test('independent oracle reconstructs the literal 49-point neighborhood and irregular ordered memberships', () => {
  const rows: Array<[number, number[]]> = [
    [-20, [0]], [-15, [-10, -5, 0, 5, 10]], [-10, [-15, -10, -5, 0, 5, 10, 15]],
    [-5, [-15, -10, -5, 0, 5, 10, 15]], [0, [-20, -15, -10, -5, 0, 5, 10, 15, 20]],
    [5, [-15, -10, -5, 0, 5, 10, 15]], [10, [-15, -10, -5, 0, 5, 10, 15]], [15, [-10, -5, 0, 5, 10]], [20, [0]],
  ]
  const expected = rows.flatMap(([y, xs]) => xs.map(x => ({ x: 120 + x, y: 112 + y })))
    .map((point, index) => ({ point_id: `p${index}`, ...point }))
  const payload = latticePayload()
  expect(attentionSnapshotFromAttachment(oracleAttachment(payload)).capture.points).toEqual(expected)
  payload.capture.point_encoding.overrides = [{ index: 0, point: { point_id: 'override', x: 1.5, y: 2.25 } }]
  payload.capture.point_encoding.additional_points = [{ point_id: 'extra', x: 3, y: 4 }]
  payload.capture.sampled_points = 50
  payload.capture.complete = false
  payload.focus = { event_id: 'focus-1', sequence: 1, focused_at: payload.created_at, realm_time_ms: 1, candidate_id: 'target-1', path_indices: [0, 1], summary: { name: 'Focused' } }
  payload.omissions = [{ reason: 'child-timeout', point_id: 'extra', mount_id: 'child-1' }]
  payload.candidates[0].sample_refs = [[2, 3], 'focus-1', 49, 0]
  const expanded = attentionSnapshotFromAttachment(oracleAttachment(payload))
  expect(expanded.capture.points).toEqual([{ point_id: 'override', x: 1.5, y: 2.25 }, ...expected.slice(1), { point_id: 'extra', x: 3, y: 4 }])
  expect(expanded.candidates[0].sample_point_ids).toEqual(['p2', 'p3', 'p4', 'focus-1', 'extra', 'override'])
  expect(expanded.focus?.path).toEqual(expanded.candidates[0].path)
  expect(expanded.focus?.focused_at).toBe(payload.created_at)
  expect(expanded.omissions).toEqual(payload.omissions)
})

test('independent oracle losslessly expands packed v3 path geometry and action identity', () => {
  const payload = packedV3Payload()
  payload.path_dictionary[1][3] = {
    tag_name: 'span',
    surface_id: 'surface-1',
    rect: [10, 20, 80, 24],
    clip_rect: [12, 20, 76, 24],
    local_to_parent: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 10, 20, 0, 1],
    coordinate_quality: 'exact',
  }
  const expandedPath = [
    { generation: 3, kind: 'host', mount_id: 'host-1' },
    {
      generation: 1,
      kind: 'element',
      mount_id: 'leaf-1',
      tag_name: 'span',
      surface_id: 'surface-1',
      rect: { x: 10, y: 20, width: 80, height: 24 },
      clip_rect: { x: 12, y: 20, width: 76, height: 24 },
      local_to_parent: {
        matrix: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 10, 20, 0, 1],
        convention: 'dommatrix-column-major',
        direction: 'local-to-parent',
      },
      coordinate_quality: 'exact',
    },
  ]
  payload.candidates[0].action_ref.path_digest = `sha256:${createHash('sha256').update(oracleCanonicalJson(expandedPath)).digest('hex')}`
  const expanded = attentionSnapshotFromAttachment(oracleAttachment(payload, 3))
  expect(expanded.candidates[0].path).toEqual(expandedPath)
  expect(expandAttentionV3ForTest(payload)).toEqual(expanded)
})

for (const [name, segment] of [
  ['short tuple', ['host', 'host-1', 3]],
  ['null attributes', ['host', 'host-1', 3, null]],
  ['unknown attribute', ['host', 'host-1', 3, { unknown: true }]],
  ['negative rectangle', ['host', 'host-1', 3, { rect: [0, 0, -1, 1] }]],
  ['short transform', ['host', 'host-1', 3, { local_to_parent: Array(15).fill(0) }]],
  ['invalid quality', ['host', 'host-1', 3, { coordinate_quality: 'estimated' }]],
] as Array<[string, unknown]>) {
  test(`independent oracle rejects packed v3 ${name}`, () => {
    const payload = packedV3Payload()
    payload.path_dictionary[0] = segment
    expect(() => expandAttentionV3ForTest(payload)).toThrow()
  })
}

const malformedCompactCases: Array<[string, (payload: any) => void]> = [
  ['negative path', p => p.candidates[0].path_indices = [-1]],
  ['fractional path', p => p.candidates[0].path_indices = [0, 0.5]],
  ['unknown path', p => p.candidates[0].path_indices = [0, 2]],
  ['unused dictionary', p => p.path_dictionary.push({ kind: 'element', mount_id: 'unused', generation: 1 })],
  ['duplicate dictionary', p => p.path_dictionary.push(p.path_dictionary[0])],
  ['dictionary order', p => p.candidates[0].path_indices = [1, 0]],
  ['dual paths', p => p.candidates[0].path = []],
  ['dual points', p => p.capture.points = []],
  ['sample overflow', p => p.candidates[0].sample_refs = [[48, 2]]],
  ['empty range', p => p.candidates[0].sample_refs = [[0, 0]]],
  ['fractional range', p => p.candidates[0].sample_refs = [[0, 1.5]]],
  ['duplicate membership', p => p.candidates[0].sample_refs = [0, [0, 2]]],
  ['unknown observation', p => p.candidates[0].sample_refs = ['missing']],
  ['point ID is not an observation', p => p.candidates[0].sample_refs = ['p0']],
  ['override out of range', p => p.capture.point_encoding.overrides = [{ index: 49, point: { point_id: 'bad', x: 0, y: 0 } }]],
  ['duplicate override', p => p.capture.point_encoding.overrides = [0, 0].map(index => ({ index, point: { point_id: 'bad', x: 0, y: 0 } }))],
  ['point identity collision', p => {
    p.capture.point_encoding.additional_points = [{ point_id: 'p0', x: 1, y: 1 }]
    p.capture.sampled_points = 50
  }],
  ['observation collision', p => p.recent_events = [{ event_id: 'p0', candidate_ids: [] }]],
  ['grid overflow', p => {
    p.capture.radius_css_px = 100
    p.capture.grid_step_css_px = 1
  }],
  ['point count mismatch', p => p.capture.sampled_points++],
  ['action digest', p => p.candidates[0].action_ref.path_digest = `sha256:${'0'.repeat(64)}`],
  ['action mount', p => p.candidates[0].action_ref.mount_id = 'wrong'],
  ['action rectangle', p => p.candidates[0].action_ref.rect.x++],
  ['action root', p => p.candidates[0].action_ref.snapshot_id = 'wrong'],
  ['duplicate candidate', p => p.candidates.push(structuredClone(p.candidates[0]))],
  ['path limit', p => p.candidates[0].path_indices = Array(33).fill(0)],
  ['dictionary limit', p => p.path_dictionary = Array(4129).fill(p.path_dictionary[0])],
  ['candidate limit', p => p.candidates = Array(129).fill(p.candidates[0])],
  ['event limit', p => p.recent_events = Array(33).fill({ event_id: 'e', candidate_ids: [] })],
  ['omission limit', p => p.omissions = Array(129).fill({ reason: 'response-budget' })],
]

for (const [name, mutate] of malformedCompactCases) {
  test(`independent oracle rejects ${name}`, () => {
    const payload = latticePayload()
    mutate(payload)
    expect(() => expandAttentionV2ForTest(payload)).toThrow()
  })
}

test('independent oracle preserves repeated valid path indices and exact expanded-byte boundary', () => {
  const payload = latticePayload()
  payload.candidates[0].path_indices = [...Array(31).fill(0), 1]
  const path = [...Array(31).fill(payload.path_dictionary[0]), payload.path_dictionary[1]]
  payload.candidates[0].action_ref.path_digest = `sha256:${createHash('sha256').update(oracleCanonicalJson(path)).digest('hex')}`
  const expanded = expandAttentionV2ForTest(payload)
  const size = Buffer.byteLength(oracleCanonicalJson(expanded))
  expect(expandAttentionV2ForTest(payload, size)).toEqual(expanded)
  expect(() => expandAttentionV2ForTest(payload, size - 1)).toThrow()
})

test('independent oracle preserves Web Fragment metadata and distinct focus ancestry', () => {
  const payload = latticePayload()
  const fragment = { kind: 'web-fragment', mount_id: 'fragment-1', generation: 2, package_id: 'fixture/nested@1', artifact_id: 'artifact-1', label: 'Nested fragment', coordinate_quality: 'exact', local_to_parent: { matrix: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 5, 10, 0, 1], convention: 'dommatrix-column-major', direction: 'local-to-parent' } }
  const focusedLeaf = { kind: 'element', mount_id: 'focus-leaf', generation: 3, tag_name: 'input' }
  payload.path_dictionary = [payload.path_dictionary[0], fragment, payload.path_dictionary[1], focusedLeaf]
  payload.candidates[0].path_indices = [0, 1, 2]
  const path = payload.path_dictionary.slice(0, 3)
  payload.candidates[0].action_ref.path_digest = `sha256:${createHash('sha256').update(oracleCanonicalJson(path)).digest('hex')}`
  payload.focus = { event_id: 'focus-1', sequence: 3, focused_at: payload.created_at, realm_time_ms: 7, path_indices: [0, 1, 3], summary: { name: 'Other focus' } }
  const expanded = attentionSnapshotFromAttachment(oracleAttachment(payload))
  expect(expanded.candidates[0].path[1]).toEqual(fragment)
  expect(expanded.focus?.path).toEqual([payload.path_dictionary[0], fragment, focusedLeaf])
  expect(expanded.focus?.focused_at).toBe(payload.created_at)
})

test('independent oracle enforces membership bounds before range expansion', () => {
  const payload = compactPayload()
  payload.capture.points = Array.from({ length: 4096 }, (_, index) => ({ point_id: index.toString(36), x: 0, y: 0 }))
  payload.capture.sampled_points = 4096
  payload.candidates[0].sample_refs = [[0, 4096]]
  for (let index = 1; index < 4; index++) {
    const candidate = structuredClone(payload.candidates[0])
    delete candidate.action_ref
    candidate.target_id = `target-${index + 1}`
    payload.candidates.push(candidate)
  }
  expect(expandAttentionV2ForTest(payload).candidates.reduce((sum, candidate) => sum + candidate.sample_point_ids.length, 0)).toBe(16384)
  payload.candidates.push({ ...payload.candidates[1], target_id: 'overflow', sample_refs: [0] })
  expect(() => expandAttentionV2ForTest(payload)).toThrow()
  payload.candidates = [payload.candidates[0]]
  payload.recent_events = [{ event_id: 'event-1', candidate_ids: ['target-1'] }]
  payload.candidates[0].sample_refs.push('event-1')
  expect(() => expandAttentionV2ForTest(payload)).toThrow()
})

test('independent oracle rejects corrupt envelopes and verifies mixed expansion budgets', () => {
  const valid = oracleAttachment()
  for (const changed of [
    { content_bytes: valid.content_bytes + 1 }, { content_hash: `sha256:${'0'.repeat(64)}` },
    { version: 1 }, { version: 3 }, { content_type: 'text/plain' }, { content: `${valid.content} ` },
  ])
    expect(() => attentionSnapshotFromAttachment({ ...valid, ...changed } as ContextAttachment)).toThrow()
  const payload = latticePayload()
  payload.capture.radius_css_px = 31
  payload.capture.grid_step_css_px = 1
  // Independently enumerated accepted row widths for the 31-pixel test lattice.
  let count = 0
  for (let y = -31; y <= 31; y++)
    count += 2 * Math.floor(Math.sqrt(31 * 31 - y * y)) + 1
  payload.capture.sampled_points = count
  payload.candidates[0].sample_refs = [[0, count]]
  const expanded = expandAttentionV2ForTest(payload)
  const size = Buffer.byteLength(oracleCanonicalJson(expanded))
  const permitted = Math.floor(ATTENTION_ORACLE_LIMITS.expanded / size)
  const attachments = Array.from({ length: permitted + 1 }, (_, index) => oracleAttachment(payload, 2, `compact-${index}`))
  expect(attentionSnapshotsFromAttachments(attachments.slice(0, permitted))).toHaveLength(permitted)
  expect(() => attentionSnapshotsFromAttachments(attachments)).toThrow()
  const v1 = oracleAttachment(attentionSnapshotFromAttachment(valid), 1, 'v1')
  expect(attentionSnapshotsFromAttachments([v1, valid])).toHaveLength(2)
  expect(attentionSnapshotsFromAttachments([valid, v1])).toHaveLength(2)
})

test('independent oracle checks the complete 16KiB envelope rather than only compact content', () => {
  const payload = compactPayload()
  const first = payload.candidates[0]
  payload.candidates = Array.from({ length: 32 }, (_, index) => {
    const candidate = structuredClone(first)
    candidate.target_id = `target-${index}`
    candidate.summary.text = ''
    delete candidate.action_ref
    return candidate
  })
  let attachment = oracleAttachment(payload)
  for (const candidate of payload.candidates) {
    const gap = ATTENTION_ORACLE_LIMITS.envelopeV2 - Buffer.byteLength(oracleCanonicalJson(attachment))
    if (gap <= 0)
      break
    candidate.summary.text = 'a'.repeat(Math.min(512, gap))
    attachment = oracleAttachment(payload)
  }
  expect(Buffer.byteLength(oracleCanonicalJson(attachment))).toBe(16384)
  expect(attentionSnapshotFromAttachment(attachment).candidates).toHaveLength(32)
  payload.candidates[31].summary.text += 'a'
  const excessive = oracleAttachment(payload)
  expect(Buffer.byteLength(excessive.content)).toBeLessThan(16384)
  expect(() => attentionSnapshotFromAttachment(excessive)).toThrow()
})

test('independent oracle charges mixed v1 and v2 bodies against one expansion budget in either order', () => {
  const dense = (radius: number) => {
    const value = latticePayload()
    value.capture.radius_css_px = radius
    value.capture.grid_step_css_px = 1
    let count = 0
    for (let y = -radius; y <= radius; y++)
      count += 2 * Math.floor(Math.sqrt(radius * radius - y * y)) + 1
    value.capture.sampled_points = count
    value.candidates[0].sample_refs = [[0, count]]
    return oracleAttachment(value, 2, `radius-${radius}`)
  }
  const first = dense(31)
  const firstSize = Buffer.byteLength(oracleCanonicalJson(attentionSnapshotFromAttachment(first)))
  let second = dense(1)
  let combined = 0
  for (let radius = 30; radius >= 1; radius--) {
    const candidate = dense(radius)
    const size = firstSize + Buffer.byteLength(oracleCanonicalJson(attentionSnapshotFromAttachment(candidate)))
    if (size < ATTENTION_ORACLE_LIMITS.expanded) {
      second = candidate
      combined = size
      break
    }
  }
  expect(combined).toBeGreaterThan(0)
  const v1 = attentionSnapshotFromAttachment(oracleAttachment())
  while (Buffer.byteLength(oracleCanonicalJson(v1)) <= ATTENTION_ORACLE_LIMITS.expanded - combined) {
    const candidate = structuredClone(v1.candidates[0])
    candidate.target_id = `padding-${v1.candidates.length}`
    delete candidate.action_ref
    candidate.summary!.text = 'x'.repeat(512)
    v1.candidates.push(candidate)
  }
  const plain = oracleAttachment(v1, 1, 'plain')
  expect(Buffer.byteLength(oracleCanonicalJson([first, second, plain]))).toBeLessThan(32768)
  expect(attentionSnapshotsFromAttachments([first, second])).toHaveLength(2)
  expect(() => attentionSnapshotsFromAttachments([plain, first, second])).toThrow()
  expect(() => attentionSnapshotsFromAttachments([first, second, plain])).toThrow()
})

test('canonical staging uses UTF-8 key order and stable array bytes', () => {
  const value = { '\u{10000}': 1, '\uE000': 2, 'a': 'Zażółć 😀' }
  const encoded = canonicalContextValue(value)
  expect(Object.keys(JSON.parse(encoded))).toEqual(['a', '\uE000', '\u{10000}'])
  expect(Buffer.byteLength(encoded)).toBeGreaterThan(encoded.length)
  expect(canonicalContextValue({ second: [value], first: true })).toBe(canonicalContextValue({ first: true, second: [value] }))
})

test('persisted context never becomes fabricated inline wire evidence', () => {
  const attachment = { attachment_id: 'attachment-1', kind: 'wippy.attention', version: 1, content: '{}' } as ContextAttachment
  const content = canonicalContextArray([attachment])
  const command: AcknowledgedSessionMessage = {
    type: 'session_message',
    message_id: 'message-1',
    request_id: 'request-1',
    session_id: 'session-1',
    data: {
      text: 'fixture',
      context_attachments_ref: { version: 1, id: 'stage-1', content_hash: `sha256:${createHash('sha256').update(content).digest('hex')}`, content_bytes: Buffer.byteLength(content) },
    },
    command_response: { type: 'command_response', success: true, request_id: 'request-1', socket_id: 'socket-1', received_at: 1 },
    persistedMessageId: 'persisted-1',
    persistedContextAttachments: [attachment],
  }
  const originalWireData = JSON.stringify(command.data)
  expect(attentionAttachment(command)).toEqual(attachment)
  expect(resolvedContextAttachments(command)).toEqual([attachment])
  expect(JSON.stringify(command.data)).toBe(originalWireData)
  expect(command.data).not.toHaveProperty('context_attachments')
  const { persistedContextAttachments: _context, ...wireOnly } = command
  expect(resolvedContextAttachments(wireOnly)).toBeUndefined()
})

for (const version of [1, 2]) {
  test(`HTTP staging v${version} metrics retain bytes and counts but no context or authenticated URLs`, async () => {
    const handlers = new Map<string, Array<(value: any) => void>>()
    const page = {
      on(name: string, callback: (value: any) => void) {
        handlers.set(name, [...(handlers.get(name) ?? []), callback])
      },
      async addInitScript() {},
    } as unknown as Page
    await installAttentionWireTap(page)
    const snapshot = {
      candidates: [{ ...(version === 1 ? { path: [{ kind: 'element', label: 'private-context-canary' }] } : { path_indices: [0] }), summary: { text: 'private-context-canary' } }],
      ...(version === 2 ? { path_dictionary: [{ kind: 'element', label: 'private-context-canary' }] } : {}),
      capture: { sampled_points: 1, ...(version === 1 ? { points: [{ point_id: 'p0', x: 1, y: 1 }] } : { point_encoding: { kind: 'css-euclidean-grid.v1', origin: { x: 1, y: 1 } } }) },
      recent_events: [],
    }
    const body = Buffer.from(JSON.stringify([{ kind: 'wippy.attention', version, content: JSON.stringify(snapshot) }]))
    const request = {
      url: () => 'https://example.test/api/v1/sessions/context?session_id=private-session-canary&request_id=00000000-0000-4000-8000-000000000001&token=private-token-canary',
      method: () => 'POST',
      postDataBuffer: () => body,
    }
    for (const handler of handlers.get('request') ?? [])
      handler(request)
    for (const handler of handlers.get('response') ?? [])
      handler({ request: () => request, status: () => 201, url: () => request.url() })
    const metrics = capturedHttpStageMetrics(page)
    expect(metrics).toHaveLength(1)
    expect(metrics[0]).toEqual(expect.objectContaining({ requestBytes: body.byteLength, attachmentCount: 1, status: 201 }))
    expect(metrics[0].attention[0]).toEqual(expect.objectContaining({ encodingVersion: version, candidateCount: 1, pathSegmentCount: 1, samplePointCount: 1, recentEventCount: 0 }))
    expect(JSON.stringify(metrics)).not.toContain('private-')
    expect(JSON.stringify(metrics)).not.toContain('example.test')
    metrics[0].status = 999
    expect(capturedHttpStageMetrics(page)[0].status).toBe(201)
  })
}
